name: Endpoint creation
description: Issue to create endpoints
title: "[ENDPOINT]: "
labels: ["backend"]
body:
  - type: markdown
    attributes:
      value: |
        This is the template to create new endpoint tickets

  - type: dropdown
    id: method
    attributes:
      label: Method
      description: Verb of the HTTP endpoint
      options:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
    validations:
      required: true

  - type: input
    id: path
    attributes:
      label: Path
      description: Path for the HTTP endpoint
    validations:
      required: true

  - type: textarea
    id: query-params
    attributes:
      label: Query params
      description: Break-line-separated list of query params in the format param_name (param_type(integer, float, string, etc)) [required]

  - type: textarea
    id: request-body
    attributes:
      label: Request body
      description: Request body JSON

  - type: textarea
    id: response-body
    attributes:
      label: Response body
      description: Response body JSON, if applicable

  - type: checkboxes
    id: allowed-roles
    attributes:
      label: Allowed roles
      options:
        - label: "All"
        - label: "Superadmin"
        - label: "Admin"
        - label: "Professional"
        - label: "Company manager"
        - label: "Sales"
        - label: "Support"
        - label: "IT"
        - label: "Patient"

  - type: textarea
    id: more-information
    attributes:
      label: More information
      description: More information that may be useful

  - type: textarea
    id: testing-strategy
    attributes:
      label: Testing strategy
      description: Type here any special, not obvious testing strategy for this endpoint

  - type: textarea
    id: release-strategy
    attributes:
      label: Release strategy
      description: Release strategy, if different than deploy when ready